##Configuration sample with RBS Change:
##@uses HeriChangeBundle
#
#heri_web_service:  
#    namespaces:             [ Heri\ChangeBundle\Service ]
#    authentication:
#        login:              wwwadmin
#        password:           abc123
#    webservices:
#        notification:
#            url:            http://erp-local.com/webservices/notification/notification
#            authentication: true
#        brand:
#            url:            http://erp-local.com/webservices/ecomwebservices/brand
#        product:
#            url:            http://erp-local.com/webservices/ecomwebservices/product
#        price:
#            url:            http://erp-local.com/webservices/ecomwebservices/price

